[package]
name = "launcherrr"
version = "0.1.0"
authors = ["Federico Dolce <psykopear@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { path = "./druid/druid", version = "0.5", features = ["svg"] }
# image = "0.23.0"
# lodepng = "2.5.0"
png = "0.15.3"
# druid = { git = "https://github.com/xi-editor/druid.git", version = "0.5" }
